name: cd

on:
  push:
    branches:
      - main

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            nvm -v
            npm -v
            yarn -v
            cd ~/node/simodang-api
            git pull origin main
            yarn install
            yarn prisma migrate deploy
            yarn prisma generate
            yarn build
            pm2 reload simodang-api
